import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#fffba7',
  '--slot4-page-text': '#3a2140',
  '--slot4-panel-bg': '#fff2b9',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#7d5a87',
  '--slot4-soft-muted-text': '#a67bad',
  '--slot4-accent': '#ffea6c',
  '--slot4-accent-fill': '#ff61f8',
  '--slot4-accent-soft': 'rgba(255, 166, 251, 0.18)',
  '--slot4-on-accent': '#161616',
  '--slot4-dark-bg': '#ff61f8',
  '--slot4-dark-text': '#fffdf8',
  '--slot4-media-bg': '#ffa6fb',
  '--slot4-cream': '#fffba7',
  '--slot4-warm': '#ffea6c',
  '--slot4-lavender': '#ffa6fb',
  '--slot4-gray': '#ffeeb0',
  '--slot4-body-gradient': 'radial-gradient(circle at top, rgba(255, 97, 248, 0.18), transparent 30%), linear-gradient(180deg, #fffba7 0%, #ffea6c 100%)',
  '--editable-page-bg': '#fffba7',
  '--editable-page-text': '#3a2140',
  '--editable-container': '1140px',
  '--editable-border': 'rgba(255, 97, 248, 0.18)',
  '--editable-nav-bg': '#ff61f8',
  '--editable-nav-text': '#3a2140',
  '--editable-nav-active': '#ffea6c',
  '--editable-nav-active-text': '#161616',
  '--editable-cta-bg': '#ff61f8',
  '--editable-cta-text': '#161616',
  '--editable-search-bg': '#fffba7',
  '--editable-footer-bg': '#ffa6fb',
  '--editable-footer-text': '#3a2140',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_16px_40px_rgba(255,97,248,0.18)]',
  shadowStrong: 'shadow-[0_28px_80px_rgba(255,97,248,0.24)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(255,251,167,0.0),rgba(255,97,248,0.75))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-12 sm:py-14 lg:py-16',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-8 lg:grid-cols-[1.15fr_0.85fr] lg:items-start',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[210px] shrink-0 snap-start sm:w-[240px]',
  },
  type: {
    eyebrow: 'text-[11px] font-extrabold uppercase tracking-[0.24em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-extrabold leading-[1.02] tracking-[-0.05em] sm:text-5xl lg:text-[3.9rem]',
    sectionTitle: 'text-3xl font-extrabold tracking-[-0.04em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-[1.5rem] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[1.5rem] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[1.6rem] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-extrabold tracking-[0.01em] text-[var(--slot4-on-accent)] transition duration-200 hover:-translate-y-0.5 hover:brightness-95 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-bold tracking-[0.01em] text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-6 py-3 text-sm font-extrabold text-[var(--slot4-on-accent)] transition duration-200 hover:-translate-y-0.5 hover:brightness-95 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[1.5rem] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[4/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1.5 hover:shadow-[0_20px_46px_rgba(0,0,0,0.26)]',
    fade: 'transition duration-300 hover:opacity-85',
  },
} as const

export const aiLayoutRules = [
  'Keep all changes inside src/editable and drive the visual system through the shared tokens first.',
  'Use a dark editorial-directory feel with contrasting image panels, dense navigation, and compact practical metadata.',
  'Preserve real fetched posts and route helpers; styling can change completely while data flow stays intact.',
  'Use multiple card types on home and archive pages so the site does not feel templated.',
  'Keep mobile layouts stacked, readable, and free from horizontal overflow.',
] as const
